publish:
  docker:
    context: ./5.0/.
    repo: kibana5
    tag:
      - $${BRANCH/master/latest}
      - $$BRANCH.build-$$BUILD_NUMBER
    force_tag: true
    registry: docker.infra.tstllc.net
    username: drone
    password: $$REGISTRY_PASS
    email: drone@tstllc.net
    storage_driver: overlay
