pipeline:
  docker:
    image: plugins/docker
    file: ./5.0/Dockerfile
    repo: docker.infra.tstllc.net/kibana5
    tag:
      - ${DRONE_BRANCH/master/latest}
      - ${DRONE_BRANCH}.build-${DRONE_BUILD_NUMBER}
    force_tag: true
    storage_driver: overlay
